from enum import Enum


class ErrorReasonCode(str, Enum):
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    EXPIRED = "EXPIRED"
    INTERNAL_PROCESSING_ERROR = "INTERNAL_PROCESSING_ERROR"
    INVALID_CALLBACK_URL_HOST = "INVALID_CALLBACK_URL_HOST"
    INVALID_CURRENCY = "INVALID_CURRENCY"
    NOT_ALLOWED = "NOT_ALLOWED"
    NOT_ALLOWED_TARGET_ENVIRONMENT = "NOT_ALLOWED_TARGET_ENVIRONMENT"
    NOT_ENOUGH_FUNDS = "NOT_ENOUGH_FUNDS"
    PAYEE_NOT_ALLOWED_TO_RECEIVE = "PAYEE_NOT_ALLOWED_TO_RECEIVE"
    PAYEE_NOT_FOUND = "PAYEE_NOT_FOUND"
    PAYER_LIMIT_REACHED = "PAYER_LIMIT_REACHED"
    PAYER_NOT_FOUND = "PAYER_NOT_FOUND"
    PAYMENT_NOT_APPROVED = "PAYMENT_NOT_APPROVED"
    RESOURCE_ALREADY_EXIST = "RESOURCE_ALREADY_EXIST"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    TRANSACTION_CANCELED = "TRANSACTION_CANCELED"

    def __str__(self) -> str:
        return str(self.value)
